// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5i3TKgtjhf8s_VQLuujfZu2IgLv1eTw',
    appId: '1:284833181275:android:f75761679e1233949b597e',
    messagingSenderId: '284833181275',
    projectId: 'cashier-app-94d1d',
    storageBucket: 'cashier-app-94d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuzpJ8jgkWwZVKW2NBq78LeUujNcj6SFQ',
    appId: '1:284833181275:ios:d0ca883788384e709b597e',
    messagingSenderId: '284833181275',
    projectId: 'cashier-app-94d1d',
    storageBucket: 'cashier-app-94d1d.firebasestorage.app',
    iosBundleId: 'com.example.cashier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_TIrEol3kNxmHKJJC0g9PAscV7hrSkQ',
    appId: '1:284833181275:web:7f006b4b0529201a9b597e',
    messagingSenderId: '284833181275',
    projectId: 'cashier-app-94d1d',
    authDomain: 'cashier-app-94d1d.firebaseapp.com',
    storageBucket: 'cashier-app-94d1d.firebasestorage.app',
    measurementId: 'G-KEKR32NJKD',
  );
}
